contact_links:
    - name: ğŸ¤” Questions and Help
      url: https://github.com/project-origin/origin-collaboration/discussions/categories/q-a
      about: This issue tracker is not for support questions. Please refer to the community's Q&A and discussion forums.
    - name: ğŸ¤ Code of Conduct
      url: https://github.com/project-origin/.github/blob/main/CODE_OF_CONDUCT.md
      about: Please consult our Code of Conduct before participating in the Project-Origin community.
    - name: ğŸ› ï¸ Contribution Guidelines
      url: https://github.com/project-origin/.github/guidelines/contribution_guidelines.md
      about: If this is your first contribution, make sure you are familiar with our Contribution Guidelines.
